name: docker-compose-action-workflow
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the task
        run: docker-compose -f docker-compose.yml up --build -d
      - name: check out the logs
        run: sleep 30 && tree
      - name: Stop the task
        run: docker-compose  -f docker-compose.yml down